version: 2

registries:
  filament:
    type: composer-repository
    url: https://packages.filamentphp.com/composer
    username: "${{ secrets.FILAMENT_USERNAME }}"
    password: "${{ secrets.FILAMENT_LICENSE_KEY }}"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - filament
